version: "3"
services:
  jenkins:
    container_name: jenkins
    image: tokdev/jenkins:1.0.0
    # image: jenkins/jenkins:2.263.1
    build:
      context: Dockerfile
    ports:
      - "8080:8080"
      - "5000:5000"
    volumes:
      # - "/home/jenkins/jenkins_home:/home/jenkins/jenkins_home:rw"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - main
    restart: always

networks:
  main:
    external:
      name: main-network