version: "3"
services:
  jenkins:
    container_name: jenkins
    image: tokdev/jenkins:1.0.0
    # image: jenkins/jenkins:2.263.1
    build:
      context: Dockerfile
    ports:
      - "8080:8080"
      - "5000:5000"
    volumes:
      # - "/var/jenkins_home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    # networks:
    #   - main
    restart: always

# networks:
#   main:
#     external:
#       name: main-network